### ISSUE TITLE
superset error when rendering visualization

### ISSUE THREAD

**Issue by Fogli** [italia/daf-dataportal#146]
while using mapbox on superset (after one or two query)
full error: 
An error occurred while rendering the visualization: Invariant Violation: Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

<img width="1420" alt="screen shot 2018-02-22 at 12 02 10" src="https://user-images.githubusercontent.com/5961482/36535031-97b291be-17c8-11e8-848e-ca5d62c522eb.png">

**Comment by giux78** [comment]
@Fogli seems to be more a superset bug may be we can see if in the superset repository there is something about. Superset is a very active open source project and most likely will be resolved.

**Comment by stevensuting** [comment]
This issue still seems to exist on 0.37.1
<img width="928" alt="Screenshot 2020-10-13 at 10 01 54 AM" src="https://user-images.githubusercontent.com/8875448/95815850-38140600-0d3b-11eb-9120-ccdf6951a97b.png">
