### ISSUE TITLE
[Ingestion Form]: error message at the last step loading open dataset

### ISSUE THREAD

**Issue by mariaclaudia** [italia/daf-dataportal#197]
### Subject of the issue
Error message displayed at the end of the metadata process loading datsset as open (organisation default_org)

### Steps to reproduce
Start the metadata process and at step One select "Aperto"  in order to add an open data dataset
Complete the metadata process
### Expected behaviour
No error message should displayed at the end because the feed is created and the process seems to be ok.

### Actual behaviour
The following message is displayed:
"Errore durante il caricamento de dataset"
But the process behind seems to be correct: the entry is displayed in the dataset list and it's possible to transfer the data.
<img width="1255" alt="screen shot 2018-03-27 at 21 54 20" src="https://user-images.githubusercontent.com/1733135/37991742-3d31e2ce-320a-11e8-912f-124854551a13.png">
Example:
*Torino consolati*
SOCI__societa.default_org_o_torino_consolati 
Pubblicato da default_org Organizzazione default_org

**Comment by mariaclaudia** [comment]
<img width="1280" alt="screen shot 2018-03-28 at 09 35 19" src="https://user-images.githubusercontent.com/1733135/38015235-731c15ba-326b-11e8-9f52-f2643de5b8f7.png">

**Comment by giux78** [comment]
Resolved
