### ISSUE TITLE
[Registration form]: not possible to complete the registration

### ISSUE THREAD

**Issue by mariaclaudia** [italia/daf-dataportal#227]
### Subject of the issue
It's not possible to register and create a daf account

### Your environment
Chrome-Version 65.0.3325.181 (Official Build) (64-bit)

### Steps to reproduce
Go to https://dataportal-private.daf.teamdigitale.it/#/register 
and fill the form in order to register

### Expected behaviour
The registration should be completed without errors

### Actual behaviour
Even if the data inserted are correct, the system returns "Errore durante la registrazione riprovare più tardi"

Please see attached
<img width="1280" alt="registrationdaf" src="https://user-images.githubusercontent.com/1733135/39307469-2b5361ac-4963-11e8-8264-2197e4b2b1c4.png">

**Comment by giux78** [comment]
Done due two impala certificates
