### ISSUE TITLE
[Superset]: A "daf_viewers" user can delete a Superset table

### ISSUE THREAD

**Issue by mariaclaudia** [italia/daf-dataportal#237]
### Subject of the issue
It's possible to delete a table in Superset with a "daf_viewers" user

### Your environment
Chrome Version 66.0.3359.170 (Official Build) (64-bit)

### Steps to reproduce
- login with an account with "daf_viewers" permission
- open Superset and go to Sources -> Tables in order to see the tables
- click on the icon "Delete record"

### Expected behaviour
It should not possible to delete a table with a "Daf_viewers" profile

### Actual behaviour
With a "daf_viewers" you can delete a record/table from superset

Please see attached the profile I used to delete a table:
![user](https://user-images.githubusercontent.com/1733135/40069045-6fcc4f36-586a-11e8-8fa3-492ce55b623d.png)

**Comment by giux78** [comment]
@mariaclaudia domani segnalalo ad andrea lui credo sappia come risolverlo

**Comment by mariaclaudia** [comment]
Fixed
