### ISSUE TITLE
Increase information in the dataset description

### ISSUE THREAD

**Issue by fabiana001** [italia/daf-dataportal#70]
Could be useful add information about how access to the dataset using jupyter.

![schermata 2017-10-12 alle 16 22 12](https://user-images.githubusercontent.com/2932983/31501259-0663ecc4-af6a-11e7-88c5-7fd0378d7c59.png)

For example, we can add the following information:

```jupyter
path_dataset = "/daf/opendata/alsia_o_atti_d_di_d_concessione1_0"
df = (spark.read.format("parquet")
     .option("inferSchema", "true")
     .option("header", "true")
     .option("sep", "|")     
     .load(path_dataset)
)
```

**Comment by fabiana001** [comment]
If you want read the impala table:

```bash
from pyspark.sql import HiveContext
hive_context = HiveContext(sc)
hive_context.sql("use opendata")
incidenti = hive_context.table('alsia_o_atti_d_di_d_concessione1_0')
incidenti
```

**Comment by fabiana001** [comment]
Better:
spark.sql("SELECT * FROM opendata.alsia_o_atti_d_di_d_concessione1_0").show()

**Comment by giux78** [comment]
Done
