### ISSUE TITLE
Login - Recupero password: wrong email address

### ISSUE THREAD

**Issue by mariaclaudia** [italia/daf-dataportal#71]
Wrong email address: email@email.com 
https://dataportal-private.daf.teamdigitale.it

<img width="562" alt="daf_private_pwd" src="https://user-images.githubusercontent.com/1733135/31506363-7df83116-af77-11e7-9e2b-756ba285f41c.png">

**Comment by giux78** [comment]
Fixed still not official emails but for sure a real contact.
