### ISSUE TITLE
Registration not work

### ISSUE THREAD

**Issue by fizzi** [italia/daf-dataportal#72]
I tried to sign up. Received the mail with the activation link. I get "Errore durante l'attivazione riprovare più tardi".

![schermata 2017-10-13 alle 09 39 39](https://user-images.githubusercontent.com/444291/31535339-0f461916-affb-11e7-963e-bcd62b9d0fc8.png)

**Comment by giux78** [comment]
We are solved some registration issue. Now you can login with email and password. Let us know if you have still problems.

**Comment by fizzi** [comment]
Now the registration signup work fine!
