### ISSUE TITLE
Insert a filter to search slices of superset

### ISSUE THREAD

**Issue by michelepetito** [italia/daf-dataportal#91]
When you are creating a new dashboard in DAF,  it would be very useful to filter slices created by superset. Now the system display all slices created in DAF and this job is very slow and cpu consumption. I suggest to generate a form filter that generate a list with these fields:
|| owner’s slice  || title of slice || type of slice || screenshot of slice ||  link preview  of slice ||

**Comment by giux78** [comment]
Done
